import type { Review } from "@/lib/types";

export const REVIEWS: Review[] = [
  {
    id: "r-la",
    author: "Gilmar Guzman",
    officeId: "la",
    language: "es",
    rating: 5,
    datePublished: "2026-02-25",
    text: "He tenido una grata experiencia con mi preparadora de documentos Veronica Velasquez. Ella me ha asesorado y preparado para la entrevista, eso me hace sentir mucha confianza. Actualizando, recibí mi residencia y seguro social al mismo tiempo. Sin duda las gestiones de Veronica Velasquez fueron de mucha ayuda para mi proceso. Recomiendo al Abogado Manuel Solis.",
    googleUrl: "https://maps.app.goo.gl/gu57uFG4eWHAQZdD9",
    featured: true,
  },
  {
    id: "r-chi",
    author: "Isabel Casco",
    officeId: "chi",
    language: "en",
    rating: 5,
    datePublished: "2026-02-18",
    text: "Im very grateful with God that after all these years I finally got my green card and that is thanks to the Manuel Solis lawyers. Especial thanks to Elizabeth Vazquez and Cesar Benitez for helping me out all these years. Its been a long process but worth it at the end.",
    // TODO: reemplazar con URL correcta de maps.app.goo.gl cuando esté disponible
  },
  {
    id: "r-har",
    author: "Wendy Alfaro",
    officeId: "har",
    language: "es",
    rating: 5,
    datePublished: "2025-03-18",
    text: "Hola recomiendo mucho el bufet de abogados Manuel Solís pues te ayudan en todo tu trámite migratorio. En mi caso recibí buena asesoría y también desde que viajas a México por tu cita consular ellos también tienen asesoría en Ciudad Juárez te ayudan con estadía, asesoría, estancia, y movimiento de transporte a todas tus citas. Lo recomiendo mucho, es lo mejor y de verdad vayan con el abogado Solís. Buena suerte a todos y no pierdan la fe porque el tiempo de Dios es maravilloso.",
    googleUrl: "https://maps.app.goo.gl/wadPG8TUHV7E7rad9",
    featured: true,
  },
  {
    id: "r-dal",
    author: "Marina Cantu",
    officeId: "dal",
    language: "es",
    rating: 5,
    datePublished: "2026-03-04",
    text: "Estamos muy contentos con el servicio del Abogado, un excelente trabajo. Incluso me dieron un tiempo estimado y se finalizó antes. Gracias por el apoyo y amabilidad, siempre atentos del equipo de Dallas. Valiosa atención de parte Maribel, Gloria y Julia L. Gracias Sr. Solis siga apoyando a nuestra gente.",
    googleUrl: "https://maps.app.goo.gl/XvuximSRNNmFbm489",
  },
  {
    id: "r-den",
    author: "Claudia Pereira",
    officeId: "den",
    language: "es",
    rating: 5,
    datePublished: "2026-02-18",
    text: "Gracias a las oficinas del abogado Manuel Solis obtuve mi residencia y proceso fue todo éxito. Agradezco la atención de la oficina de Denver y al asistente Ewdor.",
    // TODO: reemplazar con URL correcta de maps.app.goo.gl cuando esté disponible
  },
  {
    id: "r-mem",
    author: "Blanca Romero",
    officeId: "mem",
    language: "es",
    rating: 5,
    datePublished: "2026-02-18",
    text: "Excelente Servicio me encantó, estoy Totalmente Agradecida, una forma tan bonita de brindar la información de acuerdo a todo lo Solicitado. Me encantó el servicio de Sandra P. Ella muy amable muy linda llena de empatía y profesionalismo. Las oficinas muy bonito Lugar y un ambiente muy agradable!! Totalmente Recomendado",
    googleUrl: "https://maps.app.goo.gl/QHRCCbJxFkCoCKbE7",
  },
  {
    id: "r-bel",
    author: "Rogelio Rios",
    officeId: "hou-bellaire",
    language: "es",
    rating: 5,
    datePublished: "2026-01-14",
    text: "Hoy fui atendido por Gloria Briceno, excelente servicio, muy amable. Gracias señora Gloria.",
    googleUrl: "https://maps.app.goo.gl/yyuJhQDV8R6Ez5gt8",
  },
  {
    id: "r-hou",
    author: "Nancy Mendez",
    officeId: "hou-principal",
    language: "en",
    rating: 5,
    datePublished: "2026-01-21",
    text: "Martha A. Melendez was excellent in all our interviews, she was so knowledgeable and was very patient with all our questions. She was very clear in explaining and letting us know what was expected from us in putting our case together. Overall we are extremely pleased with her services. Thank you so much Martha!",
    googleUrl: "https://maps.app.goo.gl/UwkncNrYHBEVaGtw7",
    featured: true,
  },
  {
    id: "r-elp",
    author: "Ana Landeros",
    officeId: "elp",
    language: "es",
    rating: 5,
    datePublished: "2026-02-04",
    text: "La señorita Evelyn ha estado muy atenta con el caso de mi mamá. Ella siempre ha estado presente si tenemos alguna duda o simplemente dejando a saber lo que está sucediendo. Gracias a todo el equipo de Abogados, hacen un gran trabajo por ver familias reunidas.",
    googleUrl: "https://maps.app.goo.gl/mREbMXjUcFoDKxwQ6",
  },
  {
    id: "r-acc",
    author: "Jose Reyes",
    officeId: "hou-principal",
    language: "en",
    rating: 5,
    datePublished: "2026-01-14",
    text: "My family and I were helped by Himani Vithanage with an issue that we had with a business. We had tried other law firms but none helped us. When we got in contact with Ms. Vithanage and explained to her our problem she gladly took on our case and explained to us in detail how she would fight for us. I am glad we found an eager and willing lawyer to fight for us.",
    googleUrl: "https://maps.app.goo.gl/PbN8rR5QqbVGHRsF6",
  },
];
